version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: EventClean
    environment:
      POSTGRES_DB: EventClean
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5431:5432'
    restart: always
