-- V1 criar tabela de Evento

CREATE TABLE EVENTOS (
    ID UUID NOT NULL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO TEXT,
    IDENTIFICADOR VARCHAR(255) NOT NULL UNIQUE,
    DATAINICIO TIMESTAMP NOT NULL,
    DATAFIM TIMESTAMP NOT NULL,
    LOCAL VARCHAR(255) NOT NULL,
    ORGANIZADOR VARCHAR(255) NOT NULL,
    TIPOEVENTO VARCHAR(50) NOT NULL
)