-- criar tabela de Evento

CREATE TABLE EVENTOS (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO TEXT,
    IDENTIFICADOR VARCHAR(255) NOT NULL UNIQUE,
    DATAINICIO TIMESTAMP NOT NULL,
    DATAFIM TIMESTAMP,
    LOCAL VARCHAR(255),
    ORGANIZADOR VARCHAR(255),
    TIPOEVENTO VARCHAR(50) NOT NULL
)