-- criar tabela de Evento

CREATE TABLE EVENTOS (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO TEXT,
    IDENTIFICADOR VARCHAR(100) UNIQUE,
    DATAINICIO DATETIME NOT NULL,
    DATAFIM DATETIME,
    LOCAL VARCHAR(255),
    ORGANIZADOR VARCHAR(255),
    TIPOEVENTO ENUM('WORKSHOP', 'PALESTRA', 'MUSICA', 'SEMINARIO') NOT NULL


)